### ISSUE TITLE
Define how "spectrum" is instantiated in acoustic variants

### ISSUE THREAD

**Issue by tjueterb** [tjueterb/mitsuba3#11]
## Description

Depending on the variant, spectra are loaded differently from the scene description, see the table in [plugins/spectra](https://mitsuba.readthedocs.io/en/latest/src/generated/plugins_spectra.html) and [scene format/color spectra](https://mitsuba.readthedocs.io/en/latest/src/key_topics/scene_format.html#color-spectra)

### Define the following behavior for all acoustic variants:

- [x] A uniform spectrum defined as `<spectrum name=".." value="0.5"/>` should instantiate an `AcousticSpectrum` with value 0.5 at the minimal and maximal acoustic frequency defined in `spectrum.h` with the macros `MI_ACOUSTIC_FREQUENCY_MIN` and `MI_ACOUSTIC_FREQUENCY_MAX`
- [x] A spectrum defined as `<spectrum name=".." value="125:0.1, 250:0.2"/>` should instantiate an `AcousticSpectrum` with the frequencies and values given in the `value` field
- [x] A spectrum loaded from a file should work analogously
- [x] Loading rgb spectra should result in an error.

Note : in xml.cpp, `variant_to_color_mode()` returns `ColorMode::Spectral == False` when in acoustic variants, while `is_spectral_v<Spectrum>` evaluates to `True`. This behavior is inconsistent in `xml.cpp` and `xml_v.cpp`. However, spectrum instantiation in both files is consistent, so this is only relevant for future development. 

### Implementation steps

The xml file parsing is done in `xml.cpp`.

1. in emum ColorMode add `Acoustic`
    
    ```
    enum class ColorMode {
        Monochromatic,
        RGB,
        Spectral
    };
    ```
2. In function call in line 866, add `ColorMode::Acoustic`
    ```
    ref<Object> obj = detail::create_texture_from_spectrum(
                            name, const_value, wavelengths, values, ctx.variant,
                            within_emitter,
                            ctx.color_mode == ColorMode::Spectral,
                            ctx.color_mode == ColorMode::Monochromatic);
    ```
3. In `create_texture_from_spectrum`, add argument `bool is_acoustic_mode`
4. Modify the if/else block to intantiate the correct spectra in acoustic mode

## Checklist

- [x] My code follows the [style guidelines](https://mitsuba.readthedocs.io/en/latest/src/developer_guide.html#coding-style) of this project
- [x] My changes generate no new warnings
- [x] My code also compiles for `cuda_*` and `llvm_*` variants. If you can't test this, please leave below
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I cleaned the commit history and removed any "Merge" commits
- [x] I give permission that the Mitsuba 3 project may redistribute my contributions under the terms of its [license](https://github.com/mitsuba-renderer/mitsuba/blob/master/LICENSE)
